# Pré-processamento de dados

In [1]:
# Importando as bibliotecas necessárias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_aluno = pd.read_csv('dados/TS_ALUNO_34EM.csv', encoding='latin-1', sep=';')
df_diretor = pd.read_csv('dados/TS_DIRETOR.csv', encoding='latin-1', sep=';')

FileNotFoundError: [Errno 2] No such file or directory: 'dados/TS_ALUNO_34EM.csv'

In [ ]:
# Informações gerais sobre df_aluno
df_aluno.info()

print("================================================================================")
print("Forma do df_aluno:", df_aluno.shape)
print("================================================================================")
# Com o datset com */. para dados nulos ou brancos, é necessário substituir esses valores com NaN para facilitar a análise
df_aluno = df_aluno.replace(['.','*'], np.nan)
print("Quantidade de linhas com pelo menos um valor nulo:", df_aluno.isnull().any(axis=1).sum())

# Separação das colunas de interesse para a análise
colunasAluno_interesse = ['ID_ESCOLA', 'ID_ALUNO', 'ID_UF', 'ID_AREA', 'IN_PUBLICA', 'ID_SERIE', 'IN_PRESENCA_LP', 'IN_PRESENCA_MT', 'IN_PROFICIENCIA_LP', 'IN_PROFICIENCIA_MT', 'PROFICIENCIA_LP_SAEB',
'PROFICIENCIA_MT_SAEB', 'IN_PREENCHIMENTO_QUESTIONARIO','TX_RESP_Q01', 'TX_RESP_Q02', 'TX_RESP_Q03', 'TX_RESP_Q04', 'TX_RESP_Q05a', 'TX_RESP_Q05b', 'TX_RESP_Q05c', 'TX_RESP_Q06', 'TX_RESP_Q07a', 'TX_RESP_Q07b', 'TX_RESP_Q07c', 'TX_RESP_Q07d', 'TX_RESP_Q07e'
, 'TX_RESP_Q08', 'TX_RESP_Q09', 'TX_RESP_Q10a', 'TX_RESP_Q10b', 'TX_RESP_Q10c', 'TX_RESP_Q10d', 'TX_RESP_Q10e', 'TX_RESP_Q10f', 'TX_RESP_Q11a', 'TX_RESP_Q11b', 'TX_RESP_Q11c', 'TX_RESP_Q12b', 'TX_RESP_Q12c', 'TX_RESP_Q14', 'TX_RESP_Q15b'
, 'TX_RESP_Q16', 'TX_RESP_Q17', 'TX_RESP_Q18', 'TX_RESP_Q19', 'TX_RESP_Q21a', 'TX_RESP_Q21b', 'TX_RESP_Q21c', 'TX_RESP_Q21d', 'TX_RESP_Q21e', 'TX_RESP_Q23d', 'TX_RESP_Q24']

df_aluno = df_aluno[colunasAluno_interesse]
print("Formato para análise após a seleção das colunas de interesse:", df_aluno.shape)

<class 'pandas.DataFrame'>
RangeIndex: 2091337 entries, 0 to 2091336
Columns: 117 entries, ID_SAEB to TX_RESP_Q25
dtypes: float64(12), int64(29), str(76)
memory usage: 1.8 GB
================================================================================
Forma do df_aluno: (2091337, 117)
================================================================================
Quantidade de linhas com pelo menos um valor nulo: 1369638
Formato para análise após a seleção das colunas de interesse: (2091337, 52)

In [ ]:
# Visualização do dataset após a seleção das colunas de interesse
df_aluno.head()

,ID_ESCOLA,ID_ALUNO,ID_UF,ID_AREA,IN_PUBLICA,ID_SERIE,IN_PRESENCA_LP,IN_PRESENCA_MT,IN_PROFICIENCIA_LP,IN_PROFICIENCIA_MT,...,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q21a,TX_RESP_Q21b,TX_RESP_Q21c,TX_RESP_Q21d,TX_RESP_Q21e,TX_RESP_Q23d,TX_RESP_Q24
0,61412274,49408512,11,2,1,12,1,1,1,1,...,A,A,B,B,B,C,D,D,B,D
1,61412274,49408513,11,2,1,12,1,1,1,1,...,D,A,A,B,B,C,D,C,B,D
2,61412274,49408514,11,2,1,12,1,1,1,1,...,C,A,A,B,B,B,D,D,B,C
3,61412274,49408515,11,2,1,12,1,1,1,1,...,B,A,A,B,A,B,D,B,A,C
4,61412274,49408516,11,2,1,12,1,1,1,1,...,B,A,A,A,A,NaN,D,B,B,C

In [ ]:
df_diretor.describe()

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,IN_PREENCHIMENTO_QUESTIONARIO,ID_SERIE,...,TX_Q020,TX_Q021,TX_Q022,TX_Q023,TX_Q024,TX_Q090,TX_Q111,TX_Q113,TX_Q114,TX_Q116
count,107089.0,107089.000000,107089.000000,1.070890e+05,107089.000000,1.070890e+05,107089.000000,107089.000000,107089.000000,107089.000000,...,88348.000000,88231.000000,88204.000000,84275.000000,87865.000000,25664.000000,78549.000000,74203.000000,73667.000000,46482.000000
mean,2023.0,2.765513,31.262819,6.324814e+06,1.855158,6.143512e+07,0.946082,1.220676,0.838415,7.822167,...,15.648515,15.490089,16.828817,12.906164,42.987788,10.731024,5.219837,3.595609,10.926168,5.004475
std,0.0,1.092463,10.061756,1.635145e+03,0.351943,2.127006e+04,0.225856,0.414705,0.368072,2.831646,...,12.796004,12.878979,13.600166,13.202094,8.712613,18.852395,2.952463,1.971914,14.082516,3.034731
min,2023.0,1.000000,11.000000,6.322170e+06,1.000000,6.139821e+07,0.000000,1.000000,0.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2023.0,2.000000,24.000000,6.323322e+06,2.000000,6.141674e+07,1.000000,1.000000,1.000000,5.000000,...,8.000000,8.000000,8.000000,5.000000,40.000000,2.000000,3.000000,2.000000,0.000000,3.000000
50%,2023.0,3.000000,31.000000,6.324938e+06,2.000000,6.143519e+07,1.000000,1.000000,1.000000,9.000000,...,10.000000,10.000000,10.000000,8.000000,40.000000,5.000000,4.000000,3.000000,5.000000,4.000000
75%,2023.0,3.000000,35.000000,6.326028e+06,2.000000,6.145357e+07,1.000000,1.000000,1.000000,9.000000,...,20.000000,20.000000,20.000000,15.000000,46.000000,12.000000,7.000000,4.000000,16.000000,7.000000
max,2023.0,5.000000,53.000000,6.327738e+06,2.000000,6.147180e+07,1.000000,2.000000,1.000000,13.000000,...,60.000000,60.000000,60.000000,60.000000,60.000000,200.000000,12.000000,12.000000,50.000000,12.000000

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Configurações visuais do Seaborn
sns.set_theme(style="whitegrid")

# Apenas proficiências válidas
df_plot = df_aluno[(df_aluno['PROFICIENCIA_MT'] > 0) & (df_aluno['PROFICIENCIA_LP'] > 0)].copy()

# Mapeando o Sexo
if 'TX_RESP_Q01' in df_plot.columns:
    df_plot['Sexo'] = df_plot['TX_RESP_Q01'].map({'A': 'Masculino', 'B': 'Feminino'})

# Mapeando a Rede de Ensino
if 'IN_PUBLICA' in df_plot.columns:
    df_plot['Rede'] = df_plot['IN_PUBLICA'].map({1: 'Pública', 0: 'Privada'})


# Histograma de Matemática
plt.figure(figsize=(10, 5))
sns.histplot(df_plot['PROFICIENCIA_MT'], kde=True, color='skyblue', bins=30)
plt.title('Distribuição da Proficiência em Matemática')
plt.xlabel('Proficiência MT')
plt.ylabel('Frequência')
plt.show()

# Histograma de Língua Portuguesa
plt.figure(figsize=(10, 5))
sns.histplot(df_plot['PROFICIENCIA_LP'], kde=True, color='lightgreen', bins=30)
plt.title('Distribuição da Proficiência em Língua Portuguesa')
plt.xlabel('Proficiência LP')
plt.ylabel('Frequência')
plt.show()

if 'Sexo' in df_plot.columns:
    # Matemática por Sexo
    plt.figure(figsize=(8, 5))
    sns.boxplot(x='Sexo', y='PROFICIENCIA_MT', data=df_plot.dropna(subset=['Sexo']), palette='pastel')
    plt.title('Proficiência em Matemática por Sexo')
    plt.xlabel('Sexo')
    plt.ylabel('Proficiência Matemática')
    plt.show()
    
    # Língua Portuguesa por Sexo
    plt.figure(figsize=(8, 5))
    sns.boxplot(x='Sexo', y='PROFICIENCIA_LP', data=df_plot.dropna(subset=['Sexo']), palette='pastel')
    plt.title('Proficiência em Língua Portuguesa por Sexo')
    plt.xlabel('Sexo')
    plt.ylabel('Proficiência Língua Portuguesa')
    plt.show()

if 'Rede' in df_plot.columns:
    # Matemática por Rede
    plt.figure(figsize=(8, 5))
    sns.boxplot(x='Rede', y='PROFICIENCIA_MT', data=df_plot.dropna(subset=['Rede']), palette='Set2')
    plt.title('Proficiência em Matemática: Escola Pública vs. Privada')
    plt.xlabel('Rede de Ensino')
    plt.ylabel('Proficiência Matemática')
    plt.show()

    # Língua Portuguesa por Rede
    plt.figure(figsize=(8, 5))
    sns.boxplot(x='Rede', y='PROFICIENCIA_LP', data=df_plot.dropna(subset=['Rede']), palette='Set2')
    plt.title('Proficiência em Língua Portuguesa: Escola Pública vs. Privada')
    plt.xlabel('Rede de Ensino')
    plt.ylabel('Proficiência Língua Portuguesa')
    plt.show()

ModuleNotFoundError: No module named 'seaborn'

# Análise Exploratória

# Modelos de Machine Learning

## Modelo 1

### Construção e treinamento

### Avaliação e métricas

## Modelo 2

### Construção e treinamento

### Avaliação e métricas

## Modelo 3

### Construção e treinamento

### Avaliação e métricas

## Modelo 4

### Construção e treinamento

### Avaliação e métricas

# Comparação dos Resultados